name: Deploy to Cloudways

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rsync and sshpass
        run: sudo apt-get update && sudo apt-get install -y rsync sshpass

      - name: Deploy via rsync
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          APP_ROOT: ${{ secrets.APP_ROOT }}
        run: |
          sshpass -p "$SERVER_PASSWORD" rsync -av --delete \
            --no-times --omit-dir-times --no-perms --no-owner --no-group \
            --exclude ".git" --exclude ".github" \
            ./ "$SERVER_USER@$SERVER_HOST:$APP_ROOT"/
name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rsync deploy over SSH
        uses: easingthemes/ssh-deploy@v5.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          ARGS: -avz --delete --exclude ".git" --exclude ".github" 
          SOURCE: "./"
          TARGET: ${{ secrets.REMOTE_PATH }}

      - name: Reload NGINX (optional)
        if: ${{ secrets.RELOAD_CMD != '' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: ${{ secrets.RELOAD_CMD }}
