name: Deploy to Cloudways

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rsync and sshpass
        run: sudo apt-get update && sudo apt-get install -y rsync sshpass

      - name: Prime known_hosts for SSH
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy via rsync
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          APP_ROOT: ${{ secrets.APP_ROOT }}
        run: |
          sshpass -p "$SERVER_PASSWORD" rsync -av --delete \
            --no-times --omit-dir-times --no-perms --no-owner --no-group \
            --exclude ".git" --exclude ".github" \
            -e "ssh -o StrictHostKeyChecking=accept-new -o PreferredAuthentications=password -o PubkeyAuthentication=no" \
            ./ "$SERVER_USER@$SERVER_HOST:$APP_ROOT"/

      - name: Verify files on server
        if: always()
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          APP_ROOT: ${{ secrets.APP_ROOT }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=accept-new -o PreferredAuthentications=password -o PubkeyAuthentication=no \
            "$SERVER_USER@$SERVER_HOST" "ls -la \"$APP_ROOT\" | head -n 30"
